export const GET_CITIES = 'GET_CITIES';
export const ADD_CITY = 'ADD_CITY';
export const DELETE_CITY = 'DELETE_CITY';
export const CITIES_LOADING = 'CITIES_LOADING';

export const GET_ITINERARIES= 'GET_ITINERARIES';
export const ADD_ITINERARY = 'ADD_ITINERARY';
export const DELETE_ITINERARY = 'DELETE_ITINERARY';
export const ITINERARIES_LOADING = 'ITINERARIES_LOADING';